### ISSUE TITLE
Error while trying to create embeddings

### ISSUE THREAD

**Issue by abdcef** [pgrennin/ai_question_answer_web_template#1]
I get this error when I try to create embeddings:
`Creating embeddings for file: /app/app/models/../assets/raw/.DS_Store and saving to: /app/app/models/../assets/embeddings//.DS_Store.embedding.pkl
Creating embeddings...
Traceback (most recent call last):
  File "/app/create_embeddings.py", line 11, in <module>
    EmbeddingsService.create_embeddings(filename_to_embed)
  File "/app/app/models/embeddings_service.py", line 27, in create_embeddings
    EmbeddingsService.create_embeddings_for_file(file)
  File "/app/app/models/embeddings_service.py", line 40, in create_embeddings_for_file
    EmbeddingsService.create_embeddings_and_save(raw_file_path, embedded_file_path)
  File "/app/app/models/embeddings_service.py", line 49, in create_embeddings_and_save
    file_to_split = f.read()
                    ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
ERROR conda.cli.main_run:execute(47): `conda run python /app/create_embeddings.py` failed. (See above for error)`

**Comment by abdcef** [comment]
Also, I don't get any response when I try to question the included embeddings.
![CleanShot 2023-02-24 at 21 18 24](https://user-images.githubusercontent.com/56148250/221188276-b5e280b9-47f1-4cc9-9293-d5158e976665.png)

**Comment by pgrennin** [comment]
Hi @abdcef , 

According to the error you have a '.DS_Store' file in the embeddings directly.  Please remove that and try again.  Here's how  to delete that file (https://stackoverflow.com/a/30483727/3858363).

**Comment by pgrennin** [comment]
I was able to ask question on the latest build with same document and question.  It may take a few seconds for the response after hitting submit.  If you still encounter the issue please provide the logs and error message from the server running in Docker.

![image](https://user-images.githubusercontent.com/8247655/221869533-710e0dca-ba6a-4d85-810f-b3345fbefba4.png)

**Comment by pgrennin** [comment]
Thanks for trying it out.  Let me know if you have any other issues.
